cmake_minimum_required(VERSION 3.13)

include(JmfBuildType)
include(JmfMacroCommons)

set(JMF_PRJ_ROOT_DIR $ENV{JMF_PRJ_ROOT_DIR} )
get_filename_component(JMF_PRJ_ROOT_DIR ${JMF_PRJ_ROOT_DIR} ABSOLUTE)

set(JMF_TARGET_SUPPLIER $ENV{JMF_TARGET_SUPPLIER})
set(JMF_PRODUC_BRAND $ENV{JMF_PRODUC_BRAND})
set(JMF_INSTALL_APPS $ENV{JMF_INSTALL_APPS})
set(JMF_INSTALL_LIBS $ENV{JMF_INSTALL_LIBS})

set(JMF_BUILD_OUTPUT_ROOT_DIR ${CMAKE_SOURCE_DIR}/output/${JMF_PRODUCT_PLAT}/${JMF_BUILD_TYPE_DIR})
set(JMF_BUILD_OUTPUT_SANDBOX_DIR ${JMF_BUILD_OUTPUT_ROOT_DIR}/sandbox)
SET_IF_NOT_DEFINED(JMF_INSTALL_PREFIX ${JMF_BUILD_OUTPUT_SANDBOX_DIR})
set(CMAKE_INSTALL_PREFIX ${JMF_INSTALL_PREFIX})

install(PROGRAMS 
        CONFIGURATIONS Debug DebugFull Release
        DESTINATION ${JMF_BUILD_OUTPUT_SANDBOX_DIR}
        )
