CMAKE_MINIMUM_REQUIRED(VERSION 3.13)

SET(JMF_OS_TYPE posix)
ADD_DEFINITIONS(-Wa,--noexecstack)
SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -pthread -Wl,-z,noexecstack")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pthread -Wl,-z,noexecstack")
